### ISSUE TITLE
Babelrc update

### ISSUE THREAD

**Issue by hzoo** [zackify/legible#1]
The transform-async plugin actually just imports the syntax so you'll want to use http://babeljs.io/docs/plugins/transform-async-to-generator. And regenerator is included in es2015 so you can remove that. 😄

**Comment by zackify** [comment]
Oops, my bad! I'll get right on that.

**Comment by zackify** [comment]
Alright, I switched to just that plugin, and since I wasn't using the other two either I got rid of them. Thanks.

**Comment by hzoo** [comment]
Cool!

I might even suggest using http://babeljs.io/docs/plugins/preset-latest or https://github.com/babel/babel-preset-env later
